### ISSUE TITLE
Reference it in Vim Awesome

### ISSUE THREAD

**Issue by JulioJu** [sharat87/roast.vim#11]
Hi!

Your very good plugin could be referenced in https://vimawesome.com/ ? See https://vimawesome.com/submit 

I say that because your plugin is very cool ;-).

Thanks in advance !

**Comment by sharat87** [comment]
Thanks for the suggestion and the kind words! I've made the submission. Let's see (fingers crossed). :)

**Comment by JulioJu** [comment]
Sorry, vim-awesome seems to be dead… So sad ! Not updated seen lot of time…
