### ISSUE TITLE
Host Header is append to the url of the request (and should not)

### ISSUE THREAD

**Issue by JulioJu** [sharat87/roast.vim#14]
Hi!

Following example
```
Host: wwww.google.fr

GET http:///essai
```

Give the following error:

```
Error detected while processing function roast#run:                                                                                                                                                                                    
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/julioprayer/.vim/plugged/roast.vim/python3/roast.py", line 34, in run
    response = sessions[vim.current.buffer.number].send(request.prepare())
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'wwww.google.fr/http://google.fr'
Press ENTER or type command to continue
```

But the following works and trigger an HTTP GET to http://google.fr/essai:

```
Host: http://google.fr

GET /essai
```

Note: preceding example it's not accordingly with the HTTP specification. `Host` should `specifies the domain name of the server (for virtual hosting), and (optionally) the TCP port number on which the server is listening.`, it should not contains any protocol. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

If I understand well the help, and especially `:help roast-tips`, probably it's the intended behaviour. But as I said it's in contradiction with the specification.

Maybe, to have this behaviour it could be cool to change it with a new fake request HEADER like:
`VimRoastPluginBaseurl: http://google.fr`. 

As it we could keep a `Host:` header that is the same as the `Host:` header make by a browser (Firefox, Chromium).

**Comment by sharat87** [comment]
Thanks for reporting this. I've never realized the Host header value I'm showing off is against the spec. I've just pushed a fix for this. There's two parts to the fix:

Firstly, if the value of the Host header conforms to the spec, it is **not** removed from the request sent. It is still removed if it doesn't, so as to not break existing behavior.

Secondly, I like your idea of having a different method of setting the URL prefix. But I didn't want to mix it with headers syntax, so I introduced the `use` keyword. Now we can set the URL prefix like the following:

    use url_prefix https://httpbin.org

It can be unset with a line having just `use url_prefix`. This will allow us to have more configurable features in the future too.

Please test it out and let me know. I'll keep the issue open until then.

**Comment by JulioJu** [comment]
Thanks a lot ! Works well.

Sorry for the delay.
