### ISSUE TITLE
Unset header

### ISSUE THREAD

**Issue by JulioJu** [sharat87/roast.vim#15]
Hi !

Maybe it could be cool to unset header like curl done.

```
Test: test

GET http://www.google.fr

# On the following request, we don't want the header field `Test: test` defined on the first line
# In curl, declare an header field empty don't add the header

Test:


GET http://www.google.com

```

See also https://github.com/sharat87/roast.vim/issues/13#issuecomment-495708622 . As I said in this comment `curl http://google.com` appends some headers automatically like `Accept: */*`. To remove it simply use
`curl http://google.com -H 'Accept`. In Wireshark we see that the header Accept is not append.

Have the feature to have Global definition and local definition of headers could also be a solution https://github.com/diepm/vim-rest-console#52-global-definitions

**Comment by sharat87** [comment]
Removing headers by not giving a value to the right of a header name is already a feature of Roast. However, looks like it stopped working some time ago and I never realized it. I fixed it now and also added a test so it doesn't come back.

I personally don't like the idea of separate global and local header definitions. It's confusing as when we look at a header line we can't immediately tell whether it will apply to a request or not. In the same vein, appending some headers automatically also doesn't seem like a good idea. We can always add the headers we want always in a few lines at the top of the roast file and that will keep the details of the requests explicit.

When I use roast, I test out a API call and see how it behaves and then translate that request into code to make that request. If roast did some hidden shenanigans that are not visible to me, I'll miss doing those shenanigans in my application code. That will result in a lot of hair pulled apart.

Thank you for all your issues and suggestions, but sorry to be turning them down. Please don't let me discourage you. Your inputs are always welcome :).

**Comment by JulioJu** [comment]
So cool :-)
