### ISSUE TITLE
Problems with posting json with roast.vim

### ISSUE THREAD

**Issue by vendion** [sharat87/roast.vim#3]
Using `roast.vim` to try and post a json string, causes roast.vim to error out:

```
Error detected while processing function roast#run:
line    1:                                                                                      
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vendion/.vim/plugged/roast.vim/python3/roast.py", line 31, in run
    request = roast_api.build_request(vim.current.buffer, vim.current.range.end)
  File "/home/vendion/.vim/plugged/roast.vim/python3/roast_api.py", line 74, in build_request
    body = body.format(**variables)
KeyError: '"foo"'
```

The request that I tried to make is below:

```
POST http://httpbin.org/post << body
{"foo":"bar"}
body
```

I've tried escaping the double quotes with a backslash `\` with no luck
```
POST http://httpbin.org/post << body
{\"foo\":\"bar\"}
body
```

As well as wrapping the who json string in single quotes without luck as well.

**Comment by sharat87** [comment]
Try this:

```
POST http://httpbin.org/post << body
{{"foo":"bar"}}
body
```

Braces are used for variable interpolation and so should be escaped by doubling them.

I should probably improve the error message and come up with a better solution for this use case though.

**Comment by vendion** [comment]
Thanks for that I didn't think the variable interpolation also happens in heredocs (makes since for it to thinking back on it) just not vary obvious this is the case. At the very least this part of the help doc should have been a clue to that https://github.com/sharat87/roast.vim/blob/master/doc/roast.txt#L158 but wasn't very obvious to me

**Comment by sharat87** [comment]
Yeah this is a slightly quirky part of the syntax but it's a trade-off I decided to go ahead with. That part of the documentation appears good enough to me, but that's probably because I wrote it. Would it be possible for you to suggest an improvement or explain which part of the wording was confusing so I can improve it?

Thank you!
